version: '3'
services:
  # react-app:
  #   image: node:latest
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/app
  #   working_dir: /app
  #   command: npm start
  #   depends_on:
  #     - node-server
  node-server:
    image: node:latest
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    working_dir: /app
    command: npm start
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  # mobile-app:
  #   image: node:latest
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #     - ./cocktails:/app
  #   working_dir: /app
  #   command: npm run ios
  #   depends_on:
  #     - node-server
